name: shell command

on : [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo command
              run: echo "Namaste Bharat"

            - name: version of npm
              run: | 
                npm -v
                node -v

            - name: python command
              run: |
                import platform
                print(platform.processor())
             shell: python