name: shell command

on : [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo command
              run: echo "Namaste Bharat"

            - name: version of npm
              run: npm -v

            - name: version of nodejs
              run: node -v

            - name: version of python
              run: python -v

            - name: version of terraform 
              run: terrform -v

            - name: version of helm 
              run: helm -v
            
